baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Knot'

[outputs]
  home = ['HTML', 'JSON']

[params]
  githubURL = "https://github.com/paularlott/knot"
  copyright = "Paul Arlott"

  currentVersion = "v0.17.x"
  [[params.versions]]
    version = "v0.17.x"
    url = "/"

  [[params.versions]]
    version = "v0.18.x"
    url = "/v0.18/"

  [params.navigation]
    [[params.navigation.header]]
      name = 'Home'
      url = '/'
    [[params.navigation.header]]
      name = 'Docs'
      url = '/docs'
    [[params.navigation.header]]
      name = 'Tutorials'
      url = '/tutorials'
    [[params.navigation.header]]
      name = 'Changelog'
      url = '/changelog'

    # Static navigation links
    [[params.navigation.static]]
      name = 'Test Page'
      url = '/testing'
    [[params.navigation.static]]
      name = 'Changelog'
      url = '/changelog'

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'

[module]
  [module.hugoVersion]
    extended = true
    min = '0.146.0'

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    #style = 'catppuccin-frappe'
    noClasses = false
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    tabWidth = 2

  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = "assets/scss"
    target = "assets/scss"
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'