load_balancer: {
  label: "Load Balancer\nknot.example"
  shape: rectangle
}

server1: "Server 1"
server2: "Server 2"
server3: "Server 3"

load_balancer -> server1
load_balancer -> server2
load_balancer -> server3